### ISSUE TITLE
Can not start the application; Tells me Unknown exception error(built from source windows 10)

### ISSUE THREAD

**Issue by mundusnine** [armory3d/armorui#3]
Windows 10

Haxe Compiler 3.4.7

node v10.2.1

vs2017( v15.7.1

The [Compilation_output.txt](https://github.com/armory3d/armorui/files/2050748/Compilation_output.txt)

## Here is console output while executing: 
'ArmorUI.exe' (Win32): Loaded 'C:\armorui\build\windows-build\x64\Release\ArmorUI.exe'. Symbols loaded.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\dinput8.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Unloaded 'C:\Windows\System32\gdi32full.dll'
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Cannot find or open the PDB file.
Initializing Haxe libraries
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\InputHost.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\CoreUIComponents.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Unloaded 'C:\Windows\System32\WinTypes.dll'
Starting Kore
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\XInput1_4.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\hid.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\ResourcePolicyClient.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Unloaded 'C:\Windows\System32\ResourcePolicyClient.dll'
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_2a800e6ebddb7f48\nvldumdx.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\imagehlp.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_2a800e6ebddb7f48\nvwgf2umx.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Program Files\NVIDIA Corporation\Ansel\Tools\NvCameraWhitelisting64.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Unloaded 'C:\Program Files\NVIDIA Corporation\Ansel\Tools\NvCameraWhitelisting64.dll'
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\nvspcap64.dll'. Cannot find or open the PDB file.
The thread 0x3210 has exited with code 0 (0x0).
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\TextInputFramework.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\clbcatq.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\MMDevAPI.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\AudioSes.dll'. Cannot find or open the PDB file.
'ArmorUI.exe' (Win32): Loaded 'C:\Windows\System32\avrt.dll'. Cannot find or open the PDB file.
Falling back to the system's preferred mix format.
Could not open file prefs.json.
Exception thrown at 0x00007FFB40274008 in ArmorUI.exe: Microsoft C++ exception: Dynamic at memory location 0x0000003010CFF450.
The thread 0x1528 has exited with code 0 (0x0).
The thread 0x2704 has exited with code 1 (0x1).
The thread 0x36f4 has exited with code 1 (0x1).
The thread 0x2fd0 has exited with code 1 (0x1).
The thread 0x32f8 has exited with code 1 (0x1).
The thread 0x302c has exited with code 1 (0x1).
The thread 0x211c has exited with code 1 (0x1).
The thread 0x25c has exited with code 1 (0x1).
The thread 0x2734 has exited with code 1 (0x1).
The thread 0x1ff8 has exited with code 1 (0x1).
The thread 0x1c10 has exited with code 1 (0x1).
The thread 0x3144 has exited with code 1 (0x1).
The thread 0x236c has exited with code 1 (0x1).
The thread 0x52c has exited with code 1 (0x1).
The thread 0x283c has exited with code 1 (0x1).
The thread 0x35f0 has exited with code 1 (0x1).
The program '[13944] ArmorUI.exe' has exited with code 1 (0x1).

**Comment by luboslenco** [comment]
Heyo, `Could not open file prefs.json.` should be fixed now with https://github.com/armory3d/armorui/commit/9367899240a912cb9e43cbe548d0732511200c1f.

**Comment by mundusnine** [comment]
The app boots and works as designed. Some crashes occur see other issues.
