### ISSUE TITLE
When expanding the app window a crash occurs

### ISSUE THREAD

**Issue by mundusnine** [armory3d/armorui#4]
The error in visual studio can be seen here: 
![image](https://user-images.githubusercontent.com/29337013/40807866-7e18df42-64f3-11e8-954a-3ac61e7f37db.png)

Steps to reproduce:
1. Start the app built natively
2. Try to expand to full windowed screen by clicking the expand window button. Or by clicking alt-enter to  put the app in full-screen mode. You can also try to just resize the window by clicking and dragging on the side of the window. Try to resize the canvas under the Canvas panel also creates this issue : 
![image](https://user-images.githubusercontent.com/29337013/40791660-08cf26ba-64c6-11e8-81fa-de5e576a1f01.png)

3. Notice the crash.

When using a html5 build the  resizing the of canvas with the canvas properties doesn't cause a crash. Though, the canvas/window always remains to its default/initial size values even if the canvas properties are modified. The values at the bottom of the app representing the canvas size update but the window itself does not resize. (Tested in firefox)

**Comment by mundusnine** [comment]
When compilling with Krom a compiler error appears which is possibly the thing causing this issue : 
C:\armorui>node Kha/make krom
Creating Kha project.
Exporting asset 1 of 4 (DroidSans.ttf).
Exporting asset 2 of 4 (EmptyCanvas.json).
Exporting asset 3 of 4 (prefs.json).
Exporting asset 4 of 4 (color_wheel.png).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
**C:\armorui\Kha\Sources/kha/Display.hx:7: characters 9-20 : Type not found : DisplayImpl**
**C:\armorui\Kha\Sources/kha/Display.hx:6: lines 6-8 : Missing return: Int
C:\armorui\Kha\Sources/kha/Display.hx:11: characters 9-20 : Type not found : DisplayImpl
C:\armorui\Kha\Sources/kha/Display.hx:10: lines 10-12 : Missing return: Int
C:\armorui\Kha\Sources/kha/Display.hx:15: characters 9-20 : Type not found : DisplayImpl
C:\armorui\Kha\Sources/kha/Display.hx:14: lines 14-16 : Missing return: Int
C:\armorui\Kha\Sources/kha/Display.hx:19: characters 9-20 : Type not found : DisplayImpl
C:\armorui\Kha\Sources/kha/Display.hx:18: lines 18-20 : Missing return: Int
C:\armorui\Kha\Sources/kha/Display.hx:23: characters 9-20 : Type not found : DisplayImpl
C:\armorui\Kha\Sources/kha/Display.hx:22: lines 22-24 : Missing return: Bool
C:\armorui\Kha\Sources/kha/Display.hx:27: characters 9-20 : Type not found : DisplayImpl
C:\armorui\Kha\Sources/kha/Display.hx:26: lines 26-28 : Missing return: Int**

Haxe compiler error.

**Comment by luboslenco** [comment]
Patch opened at https://github.com/Kode/Kore/pull/270.
