### ISSUE TITLE
Could we have a place to talk about implementations related to armorUI ? Like a #Freenode

### ISSUE THREAD

**Issue by mundusnine** [armory3d/armorui#8]
Hi,

Basically I have been merging a lot of your work lately because I am developing in parallel and adding a couple of things(actually implemented a version of parenting but I prefer your implementation and have a working text area and a new ElementGroup element) and just wanted to know if there could be a communication channel in which you could express the things you want to be done and your preference on implementation( for example to stay away from certain things that we can do in haxe that are not static friendly).  I will make a pull request for the things I changed but its quite big and I guess you would probably prefer small pull requests ?.

Good day,

**Comment by luboslenco** [comment]
Hello!

Hm sorry it's my bad, did not expect much PRs here. On top that the editor is stuffed into a single `.hx` source, will try to organize it properly to ease the collaboration. Once done I will also open issues here about the planned features, so we do not end up working on the same thing.

Yes smaller PRs preferable.:) I will try to stay up more at [gitter](https://gitter.im/armory3d/armory) for chat.
